### ISSUE TITLE
0.11.x TF not supported by resource manager, and Error code: InvalidParameter(400)

### ISSUE THREAD

**Issue by alyeung** [oracle-quickstart/oci-arch-wordpress-mds#11]
Hello Jeevan,

1. I was trying your example deployment from this blog: https://blogs.oracle.com/cloud-infrastructure/post/create-your-own-web-presence-with-oracle-cloud-infrastructure-using-wordpress
2. From the readme.md, https://github.com/oracle-quickstart/oci-arch-wordpress-mds/tree/master/micro-deployment, I chose 'Deploy to Oracle Cloud'
3. It takes you to the console, https://cloud.oracle.com/resourcemanager/stacks/create?region=us-phoenix-1&zipUrl=https%3A%2F%2Fgithub.com%2Foracle-quickstart%2Foci-arch-wordpress-mds%2Freleases%2Flatest%2Fdownload%2Foci-wordpress-micro-stack-latest.zip 
4. Check the box to accept oracle terms
5. You will see a yellow warning label: '0.11.x is no longer supported.'
6. Followed by a red error bar at the lower part of the page, with the following message: (400, InvalidParameter, false) https://github.com/oracle-quickstart/oci-arch-wordpress-mds/releases/download/v1.4/oci-wordpress-micro-stack-latest.zip (opc-request-id: csidc744bfac4a8ea4881af1729c04f8/e6064b84d0e1457b8644a2d2bf515da5/B7097997E9BD123D977D8762EBEC41A5) Request ID: csidc744bfac4a8ea4881af1729c04f8/e6064b84d0e1457b8644a2d2bf515da5/F8AB00FEC2B439EA4C91AC48E12B9E8E. Timestamp: Wed, Sep 29, 2021, 04:40:53 UTC. Endpoint: https://cloud.oracle.com/resourcemanager/stacks/create. Error code: InvalidParameter(400).
7. For steps 4, 5, 6 please see the image below:

![image](https://user-images.githubusercontent.com/4118083/135204546-7a1513df-76c7-496a-b954-aa2d746abdfa.png)

**Comment by lfeldman** [comment]
I have added ORM stack zip files to the latest release. Now deploy button for micro-deployment should work fine.
