### ISSUE TITLE
 /tmp/terraform_1666793039.sh: line 3: docker-compose: command not found

### ISSUE THREAD

**Issue by jaimecid** [oracle-quickstart/oci-arch-wordpress-mds#8]
Resource Manager Job failed: ... here you have the latest lines of the logs
...
oci_core_public_ip.WordPress_public_ip: Creating...
oci_core_public_ip.WordPress_public_ip: Creation complete after 0s [id=ocid1.publicip.oc1.eu-frankfurt-1.amaaaaaalguzq5iadfhztonqczwxcnmvtp3zwd62grwk4zex62fm6e3d4uza]
data.template_file.wordpress-docker-compose: Reading...
data.template_file.wordpress-docker-compose: Read complete after 0s [id=a22841fdc930fe3404173c4a762e4d26194a2bc1303f6df55c01602b24e108ed]
null_resource.WordPress_provisioner: Creating...
null_resource.WordPress_provisioner: Provisioning with 'file'...
null_resource.WordPress_provisioner: Provisioning with 'remote-exec'...
null_resource.WordPress_provisioner (remote-exec): Connecting to remote host via SSH...
null_resource.WordPress_provisioner (remote-exec):   Host: 152.70.167.131
null_resource.WordPress_provisioner (remote-exec):   User: opc
null_resource.WordPress_provisioner (remote-exec):   Password: false
null_resource.WordPress_provisioner (remote-exec):   Private key: true
null_resource.WordPress_provisioner (remote-exec):   Certificate: false
null_resource.WordPress_provisioner (remote-exec):   SSH Agent: false
null_resource.WordPress_provisioner (remote-exec):   Checking Host Key: false
null_resource.WordPress_provisioner (remote-exec):   Target Platform: unix
null_resource.WordPress_provisioner (remote-exec): Connected!
null_resource.WordPress_provisioner: Still creating... [10s elapsed]
null_resource.WordPress_provisioner: Still creating... [20s elapsed]
null_resource.WordPress_provisioner (remote-exec): /tmp/terraform_1666793039.sh: line 3: docker-compose: command not found
Error: error executing "/tmp/terraform_1666793039.sh": Process exited with status 127

**Comment by lfeldman** [comment]
@jeevanjoseph can you please take a look at this issue?

**Comment by jeevanjoseph** [comment]
@jaimecid - this is likely caused by `yum` issues, where the docker installation fails. Can you try running a `destroy` followed by an `apply` ?
Logs from `/var/log/messages` are helpful to trouble shoot if you encounter this again, but they have to be captured soon after you see the issue.

**Comment by jaimecid** [comment]
Thanks @jeevanjoseph , i deleted everything, VCN and Compute Image and 2nd try was successful , ... i was testing in Always Free resources both times. The only difference was this second time i uploaded mykey.pub file.  BTW ,  congrats for this great WordPress micro Deployment on OCI. Great example and running on Always Free resources. @jeevanjoseph , @lfeldman  Thanks a lot !!!
